resource_group_name = "aks_terraform_rg"
location            = "Central India"
cluster_name        = "aks-terraform-cluster"
kubernetes_version  = "1.27.1"
system_node_count   = 2
node_resource_group = "aks_terraform_-node_resources_rg"
name                = "azurermcontainerregistry"
AZURE_TENANT_ID = "04319eaa-61ac-48b9-a603-123abaf6efd6"
AZURE_SUBSCRIPTION_ID = "cbace7b1-2899-469a-af59-d44869"
